cms_homepage:
    path:     /
    defaults: { _controller: CmsBundle:DashBoard:index }

cms_configuration:
    path:     /configuration
    defaults: { _controller: CmsBundle:Configuration:index }
 
affichemessage:
    path:     /view/{id}
    defaults: { _controller: FrontOfficeBundle:Default:viewMessage }