<?php

namespace FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    
    public function myFindAll(){
        return $this
                ->createQueryBuilder('a')
                ->getQuery()
                ->getResult()
                ;
    }
    
    public function myfindone($id){
        
        
    }
}
